[package]
name = "include_value"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
macro-string = "0.1"
proc-macro2 = "1.0"
quote = "1.0"
serde_json = { version = "1.0", features = ["raw_value" ]}
syn = "2.0"
